# Generated by Django 5.0.14 on 2026-08-08 10:11

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('source_url', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, choices=[('hy', 'Armenian'), ('ru', 'Russian'), ('en', 'English')], max_length=8)),
                ('car_make', models.CharField(blank=True, max_length=100)),
                ('car_model', models.CharField(blank=True, max_length=100)),
                ('car_year_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('car_year_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symptom_text', models.TextField()),
                ('confirmed_fix', models.TextField()),
                ('parts_named', models.JSONField(blank=True, default=list)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('split', models.CharField(choices=[('kb', 'Knowledge base (retrievable)'), ('eval', 'Evaluation only (never retrievable)')], default='eval', max_length=8)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='case_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
