# Generated by Django 5.0.14 on 2026-08-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caserecord',
            name='language',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='split',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='urgency',
        ),
    ]
