# Generated by Django 5.0.14 on 2026-08-08 10:11

import apps.diagnostics.models
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, choices=[('hy', 'Armenian'), ('ru', 'Russian'), ('en', 'English')], max_length=8)),
                ('car_make', models.CharField(blank=True, max_length=100)),
                ('car_model', models.CharField(blank=True, max_length=100)),
                ('car_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('raw_text', models.TextField(blank=True, help_text='Transcribed text/voice description of the problem.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('case_matched', 'Matched to a prior verified case'), ('researching', 'Deep research in progress'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('urgency', models.CharField(blank=True, choices=[('drive_it', 'Drive it'), ('fix_this_week', 'Fix this week'), ('do_not_drive', 'Do not drive')], max_length=20)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('matched_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='cases.caserecord')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.diagnostics.models.diagnostic_image_upload_to)),
                ('image_type', models.CharField(choices=[('vin_plate', 'VIN plate'), ('part', 'Old part'), ('dashboard_light', 'Dashboard warning light'), ('damage', 'Damage / leak')], max_length=20)),
                ('decoded_vin', models.CharField(blank=True, max_length=17)),
                ('decoded_data', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diagnostics.diagnosticrequest')),
            ],
        ),
    ]
