# Generated by Django 5.0.14 on 2026-08-08 11:52

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_caserecord_language_and_more'),
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticimage',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='diagnosticimage',
            name='decoded_vin',
        ),
        migrations.RemoveField(
            model_name='diagnosticrequest',
            name='language',
        ),
        migrations.RemoveField(
            model_name='diagnosticrequest',
            name='match_confidence',
        ),
        migrations.RemoveField(
            model_name='diagnosticrequest',
            name='matched_case',
        ),
        migrations.RemoveField(
            model_name='diagnosticrequest',
            name='urgency',
        ),
        migrations.CreateModel(
            name='DiagnosticCaseMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_matches', to='cases.caserecord')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_matches', to='diagnostics.diagnosticrequest')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='diagnostics.diagnosticrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='diagnosticcasematch',
            constraint=models.UniqueConstraint(fields=('request', 'case'), name='unique_diagnostic_case_match'),
        ),
    ]
