# Generated by Django 5.0.14 on 2026-08-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_remove_diagnosticimage_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticrequest',
            name='symptom_text',
            field=models.TextField(blank=True, help_text='LLM-maintained summary of the symptom, refreshed after every user turn from the full conversation so far. Embedded and matched against CaseRecord.symptom_text -- keeping both fields the same shape keeps the two embedding spaces comparable.'),
        ),
        migrations.AlterField(
            model_name='diagnosticrequest',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Transcribed text/voice description of the problem, as first submitted.'),
        ),
    ]
