# Generated by Django 5.0.14 on 2026-08-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_diagnosticrequest_symptom_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticrequest',
            name='raw_text',
        ),
        migrations.AlterField(
            model_name='diagnosticrequest',
            name='symptom_text',
            field=models.TextField(blank=True, help_text="Rolling summary of the whole conversation so far, refreshed after every user turn. Embedded and matched against CaseRecord.symptom_text -- keeping both fields the same shape keeps the two embedding spaces comparable. There is no separate 'original text' field: the first turn's content is just this field's first version."),
        ),
    ]
