# Generated by Django 5.0.14 on 2026-08-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_remove_diagnosticrequest_raw_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticmessage',
            name='embedding',
        ),
    ]
