# Generated by Django 5.0.14 on 2026-08-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_remove_diagnosticmessage_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticrequest',
            name='trace',
            field=models.JSONField(blank=True, default=list, help_text='The pipeline events from the last run -- the `step`/`llm`/`lookup`/`note` stream the UI replays to show which agents ran and what they found. Persisted because the SSE feed is live-only: without this the pipeline view would be blank for every request except the one currently being streamed.'),
        ),
    ]
