# Generated by Django 5.0.14 on 2026-08-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0006_diagnosticrequest_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='diagnostics.diagnosticrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
